# yaml-language-server: $schema=./_schema.json

name: Confirm

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: 'A token used for authorized access to Github'
        required: true
    outputs:
      should-release:
        description: 'A determination of whether or not to release'
        value: ${{ jobs.confirm.outputs.should-release }}
      pr-number:
        description: 'The PR number associated with the release (if applicable)'
        value: ${{ jobs.confirm.outputs.pr-number }}
    inputs:
      debug:
        description: Debug jobs
        default: false
        required: false
        type: boolean
      node:
        description: The version of Node.js used
        default: '23'
        required: false
        type: string
      skip:
        description: Skip jobs
        default: false
        required: false
        type: boolean

permissions:
  contents: read

env:
  # General Options
  debug: false
  # Timeouts (in minutes)
  timeout-setup: 10
  # Environment Variables
  CI: true
  CI_DEBUG: ${{ vars.CI_DEBUG }}
  CI_PR_NUMBER: ${{ github.event.pull_request.number }}
  CI_TIMEOUT_SETUP: ${{ vars.CI_TIMEOUT_SETUP }}

jobs:
  confirm:
    name: Confirm
    if: github.repository.archived != true
    runs-on: ubuntu-latest
    container:
      image: node:${{ inputs.node }}
    outputs:
      should-release: ${{ steps.confirm.outputs.result }}
      pr-number: ${{ steps.confirm.outputs.pr }}
    steps:
      - name: Init
        id: init
        run: |
          echo "__SKIP=${{ inputs.skip }}" >> $GITHUB_ENV
          echo "__DEBUG=${{ env.CI_DEBUG || env.debug || inputs.debug }}" >> $GITHUB_ENV
          echo "__TIMEOUT_SETUP=${{ env.CI_TIMEOUT_SETUP || fromJSON(env.timeout-setup) }}" >> $GITHUB_ENV

      - name: Dependencies
        id: setup
        shell: bash
        run: |
          apt-get update
          apt-get install -y jq

      - name: Confirm
        id: confirm
        timeout-minutes: ${{ fromJSON(env.__TIMEOUT_SETUP) }}
        if: fromJSON(env.__SKIP) != true
        shell: bash
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          RELEASE_BRANCH_PATTERNS="^(main|master|alpha|beta|next|next-major|\d+\.X\.X)$"

          if [[ $BRANCH_NAME =~ $RELEASE_BRANCH_PATTERNS ]]; then
            echo "Branch $BRANCH_NAME is a release, prerelease, or maintenance branch."
            echo "Current Branch: $BRANCH_NAME"
            echo "result=true" >> $GITHUB_OUTPUT
          else
            PR_LIST=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")
            echo "PR List: $PR_LIST"

            PR_DATA=$(echo "$PR_LIST" | jq -r --arg BRANCH_NAME "$BRANCH_NAME" '.[] | select(.head.ref == $BRANCH_NAME) | .number')
            echo "PR Data: $PR_DATA"

            if [[ ! -z "$PR_DATA" ]]; then
              PR_NUMBER=$PR_DATA
              echo "Open PR found for branch $BRANCH_NAME with PR number $PR_NUMBER"
              echo "result=true" >> $GITHUB_OUTPUT
              echo "pr=$PR_NUMBER" >> $GITHUB_OUTPUT
              echo "CI_PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
            else
              echo "No open PR for branch $BRANCH_NAME and it's not a release branch"
              echo "pr=-1" >> $GITHUB_OUTPUT
              echo "result=false" >> $GITHUB_OUTPUT
            fi
          fi
