# yaml-language-server: $schema=./_schema.json

name: Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

env:
  # General Options
  name: semantic-release-config
  node: '21'
  # Skip
  skip-tests: false
  skip-publish: true
  # Timeouts (in minutes)
  timeout-setup: 10
  timeout-tests: 30
  timeout-deployment: 60
  # Environment Variables
  CI_DEBUG: ${{ vars.CI_DEBUG }}
  CI_PR_TIMEOUT_SETUP: ${{ vars.CI_PR_TIMEOUT_SETUP }}
  CI_PR_TIMEOUT_TESTS: ${{ vars.CI_PR_TIMEOUT_TESTS }}
  CI_PR_TIMEOUT_DEPLOYMENT: ${{ vars.CI_PR_TIMEOUT_DEPLOYMENT}}
  CI_PR_TIMEOUT_CACHE_INVALIDATIONS: ${{ vars.CI_PR_TIMEOUT_CACHE_INVALIDATIONS }}
  CI_SKIP_PRERELEASE: ${{ vars.CI_SKIP_PRERELEASE }}
  DEBUG: ${{ vars.DEBUG }}
  NODE_ENV: production
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    name: TEST
    if: github.repository.archived != true
    uses: ./.github/workflows/test.yml
    with:
      dist: bin

  build:
    name: BUILD
    needs: [test]
    if: github.repository.archived != true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    uses: ./.github/workflows/build.yml
    with:
      dist: bin

  publish:
    name: PUBLISH
    needs: [test, build]
    if: github.repository.archived != true
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/publish.yml
    with:
      dist: bin
